apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-helloworld-deploy
  labels:
    app: nginx-helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-helloworld
  template:
    metadata:
      labels:
        app: nginx-helloworld
    spec:
      containers:
      - name: nginx
        image: gustaavolp/nginx-helloworld:
        ports:
        - containerPort: 80