apiVersion: v1
kind: Service
metadata:
  name: nginx-helloworld-service
  labels:
    app: nginx-helloworld
spec:
  selector:
    app: nginx-helloworld
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
