name: CI/CD Pipeline

on:
  push:
    branches: [main]

permissions:
  contents: write
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate IMAGE_TAG
        id: vars
        run: |
          echo "IMAGE_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build and push images
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            gustaavolp/nginx-helloworld:${{ env.IMAGE_TAG }}
            gustaavolp/nginx-helloworld:latest

  update-manifests:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for update
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Update deployment image tag
        run: |
          sed -i "s|image:.*|image: gustaavolp/nginx-helloworld:${{ env.IMAGE_TAG }}|" k8s/deployment.yaml

      - name: Commit and push manifests
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "ci: update image tag to ${{ env.IMAGE_TAG }}"
          git push origin main